exclude: [
  README.md,
  CNAME,
  Rakefile,
  src
]
permalink: pretty

collections:
  speaking:
    output: false
  podcast:
    output: false
  work:
    output: true

defaults:
  - scope:
      type: work
    values:
      layout: work
      area: work
  - scope:
      type: posts
    values:
      layout: post
      area: writing