exclude: [
  README.md,
  CNAME,
  Rakefile,
  src
]
permalink: pretty

collections:
  speaking:
    output: false
  podcast:
    output: false
  work:
    output: true

defaults:
  - scope:
      type: work
    values:
      layout: work
  - scope:
      type: speaking
    values:
      layout: talk
  - scope:
      type: podcast
    values:
      layout: podcast